name: hola-mundo
on: [push]
jobs: 
  hola-mundo:
    runs-on: ubuntu-lates
    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Hola mundo
        run: echo ! Hola Mundo ${{steps.ip.outputs.ipv4}}