name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify your required Node.js version

      - name: Install dependencies
        run: cd backend && npm install

      - name: Run tests
        run: cd backend && npm run  test
