name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd backend && npm install

      - name: Run tests
        run: cd backend && npm run test

  notify:
    if: failure()
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with: 
          server_address: smtp.gmail.com
          server_port: 587 
          username: atencionalclientelabcm@gmail.com 
          password: wicm jzvu qccz nsfq 
          subject: GitHub Actions - Test Failed 
          to: kenny.molina.murillo@gmail.com 
          from: atencionalclientelabcm@gmail.com 
          body: | 
            Tests have failed in the GitHub Actions workflow for commit ${{ github.sha }}. Please check the details in the Actions tab on GitHub.
