name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd backend && npm install

      - name: Run tests
        run: cd backend && npm run test

  notify:
    if: failure()
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Post failure comment
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "⚠️ Tests have failed for commit ${{ github.sha }}. Please check the details."
            })
